### PR TITLE
Bumping to Electron 1.2.6

### PR DESCRIPTION
**Pull request by fusion809**
Hi,

I tested the pull out on my fork of this repo, building a package from it and this Electron package I've built is working fine, running Atom fine, so I suspect I've got this bumping right. 

Hope this helps,
Brenton

### CODE REVIEW

**Comment by tensor5** [comment]
Did you really build without patches?

**Comment by fusion809** [comment]
Sure did mate (I'm Aussy, so forgive me if in your neck of the woods this has different connotations), check the source of the Electron 1.2.6, these patches have become redundant as many of your patches have become integrated into the upstream source. I even uploaded my 64-bit Electron 1.2.6 package to my PKGBUILDs repository (sorry I've ditched my fork of this repo as a site for uploading my binaries) https://github.com/fusion809/PKGBUILDs/releases/tag/current. Feel free to download it, analyse it in detail, all I know is that it is running fine and `electron --app=/usr/lib/atom-bleeding` is launching `atom-bleeding` fine.

**Comment by tensor5** [comment]
For example, if I remove `chromium-use-system-minizip.patch` then I'll get:

```
[4504/13072] CXX obj/third_party/zlib/google/zip.zip_reader.o
FAILED: obj/third_party/zlib/google/zip.zip_reader.o 
/usr/bin/clang++ -MMD -MF obj/third_party/zlib/google/zip.zip_reader.o.d -DU_COMBINED_IMPLEMENTATION -DUNISTR_FROM_CHAR_EXPLICIT= -DUNISTR_FROM_STRING_EXPLICIT= -DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=0 -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -D_FILE_OFFSET_BITS=64 -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=264915-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DUSE_X11=1 -DUSE_CLIPBOARD_AURAX11=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DENABLE_TOPCHROME_MD=1 -DUSE_UDEV -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DUSE_SYSTEM_MINIZIP -DUSE_LIBPCI=1 -DUSE_OPENSSL=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_NSS_VERIFIER=1 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen/shim_headers/libevent/target -Igen -I../.. -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -fcolor-diagnostics -g -B/build/electron/src/electron/vendor/brightray/vendor/libchromiumcontent/vendor/chromium/src/third_party/binutils/Linux_x64/Release/bin -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-unused-variable -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -m64 -march=x86-64 -O2 -fno-ident -fdata-sections -ffunction-sections -funwind-tables -O3 -Wno-error -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-exceptions -fno-rtti -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -Wno-deprecated  -c ../../third_party/zlib/google/zip_reader.cc -o obj/third_party/zlib/google/zip.zip_reader.o
../../third_party/zlib/google/zip_reader.cc:285:22: error: no matching function for call to 'unzLocateFile'
  const int result = unzLocateFile(zip_file_,
                     ^~~~~~~~~~~~~
/usr/include/minizip/unzip.h:267:20: note: candidate function not viable: no known conversion from 'const int' to 'unzFileNameComparer' (aka 'int (*)(void *, const char *, const char *)') for 3rd argument
extern int ZEXPORT unzLocateFile OF((unzFile file, const char *filename, unzFileNameComparer filename_compare_func));
                   ^
1 error generated.
```

You should make sure that with your modifications, you are not silently downloading a prebuilt `libchromiumcontent`, which is what Electron the build system does by default.

**Comment by fusion809** [comment]
Ah, sorry. Well shall await for your patch around it. These patches are too complex for me to bump sometimes.

**Comment by fusion809** [comment]
Ah, I just tried your 1.2.6 bump and it's failing. I removed those patches because they were no longer valid and causing errors. Namely atm I'm getting the error (indicating an issue with `brightray-dont-update-submodule.patch`):

```bash
Reset branch 'makepkg'
==> Starting prepare()...
patching file script/build.py
patching file electron.gyp
patching file script/bootstrap.py
patching file script/bootstrap.py
patching file toolchain.gypi
patching file script/build-libchromiumcontent.py
patching file script/bootstrap
Reversed (or previously applied) patch detected!  Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file script/bootstrap.rej
==> ERROR: A failure occurred in prepare().
    Aborting...
```

**Comment by tensor5** [comment]
You should `rm -fr src` before every build.

**Comment by fusion809** [comment]
Rofl sorry! Such a silly mistake of mine.

**Pull request closed without merging**
